apiVersion: v1
kind: Pod
metadata:
  name: toolbox
spec:
  restartPolicy: Never
  containers:
  - name: toolbox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
    image: mesosphere/aws-cli
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
